# Dependencies
markdown:        kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Urodela Games
tagline:          'Game Development by Dave McWave'
description:      'A blog by indie game dev Dave McWave <a href="https://twitter.com/urodelagames" target="_blank">@urodelagames</a>.'
url:              https://urodelagames.github.io
baseurl:          "/"

author:
  name:           'Dave McWave'
  url:            https://twitter.com/urodelagames

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - jekyll-seo-tag
  - jemoji

# Google Analytics
google_analytics: G-6LFBJ4RPL0
