# Dependencies
markdown:        kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Urodela Games
tagline:          'Game Development by David Dalisay'
description:      'A blog by indie game dev <a href="https://twitter.com/urodelagames" target="_blank">David Dalisay</a>.'
url:              https://urodelagames.github.io
baseurl:          /

author:
  name:           'David Dalisay'
  url:            https://twitter.com/urodelagames

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

# Google Analytics
google_analytics: G-6LFBJ4RPL0
